export const productsData = [
    {
        id: 1,
        name: "Almohadon Marron",
        price: 3000,
        category: "Living",
        description: "Almohadon Marron Estampado",
        image: "../src/json/media/imagenes/almohadon marron estampado.jpeg",
		rating: 5,
    },
    {
        id: 2,
        name: "Almohadon Verde",
        price: 3000,
        category: "Living",
        description: "Almohadon Verde Estampado",
        image: "../src/json/media/imagenes/almohadon verde estampado.jpeg",
		rating: 4.8,
    },
    {
        id: 3,
        name: "Almohadon Rosa",
        price: 3000,
        category: "Living",
        description: "Almohadon Rosa Estampado",
        image: "../src/json/media/imagenes/almohadonesrosa.jpeg",
		rating: 4.9,
    },
    {
        id: 4,
        name: "Almohadon Blanco",
        price: 3500,
        category: "Living",
        description: "Almohadon Blanco con tiras negras",
        image: "../src/json/media/imagenes/almohadones blanco tiras negras.jpeg",
		rating: 4.7,
    },
    {
        id: 5,
        name: "Camino de Mesa",
        price: 4500,
        category: "Cocina",
        description: "Camino de Mesa Beige",
        image: "../src/json/media/imagenes/camino mesa.jpeg",
		rating: 4.0,
    },
    {
        id: 6,
        name: "Individual Marron Claro",
        price: 2000,
        category: "Cocina",
        description: "Individual Marron Claro",
        image: "../src/json/media/imagenes/individual 2.jpeg",
		rating: 4.8,
    },
    {
        id: 7,
        name: "Individual claro",
        price: 2100,
        category: "Cocina",
        description: "Individual Beige",
        image: "../src/json/media/imagenes/individual claro.jpeg",
		rating: 4.6,
    },
    {
        id: 8,
        name: "Individual marron",
        price: 2000,
        category: "Cocina",
        description: "individual marron",
        image: "../src/json/media/imagenes/individual marron.jpeg",
		rating: 4.9,
    },
    {
        id: 9,
        name: "Manta Marron",
        price: 6500,
        category: "Dormitorio",
        description: "Manta Marron",
        image: "../src/json/media/imagenes/manta marron.jpeg",
		rating: 5.0,
    },
    {
        id: 10,
        name: "Manta beige",
        price: 6200,
        category: "Dormitorio",
        description: "Manta beige puntillas",
        image: "../src/json/media/imagenes/mantel beige puntillas.jpeg",
		rating: 5.0,
    },
    {
        id: 11,
        name: "Manta natural",
        price: 6900,
        category: "Dormitorio",
        description: "Manta natural puntillas",
        image: "../src/json/media/imagenes/mantel natural puntillas.jpeg",
		rating: 4.0,
    },
	{
        id: 12,
        name: "Set Individuales",
        price: 6500,
        category: "GiftBox",
        description: "Set 2 individuales",
        image: "../src/json/media/imagenes/individuales set.jpeg",
		rating: 5.0,
    },
    {
        id: 13,
        name: "Set Organizadores",
        price: 5500,
        category: "GiftBox",
        description: "Set organizadores hilo",
        image: "../src/json/media/imagenes/giftbox.jpeg",
		rating: 5.0,
    },
    {
        id: 14,
        name: "Set Organizadores chicos ",
        price: 6500,
        category: "GiftBox",
        description: "Set organizadores chicos Hilo",
        image: "../src/json/media/imagenes/organizadores.jpeg",
		rating: 5.0,
    },
    // samsung 
]